# -*- coding: utf-8 -*-
"""data scrubbing cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181MP_oXQBNM7mULMmlyMHQquoCAiQyiz
"""

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import rcParams
import math

import pandas as pd

ames_url = 'https://raw.githubusercontent.com/wblakecannon/ames/master/data/housing.csv'

ames = pd.read_csv(ames_url)

len(ames)

pd.options.display.max_colums = 100
ames

ames.describe()
ames.describe().round(1)
ames.iloc[:,[5,6,7,82]].describe().round(1)

ames.isnull().sum()[0:83]
pd.DataFrame(ames.isnull().sum()[0:83])

ames.iloc[:, [74,75,76,8,59]].columns

ames.loc[: ,['Pool QC', 'Fence', 'Misc Feature', 'Alley', 'Fireplace Qu']]

import matplotlib as mpl
import matplotlib as mp
import numpy as no

